# Lopende meetnetten in Vlaanderen {#lopende-meetnetten}

Het langlopend monitoren van de toestand en trend van vogels in landbouwgebied is van groot belang om inzicht te verkrijgen in de impact van landbouwpraktijken op de vogelpopulaties.
Verschillende initiatieven daarrond zijn lopend in Vlaanderen, de meest relevante projecten zijn de ABV [@onkelinx2023a], BBV en vogelatlas tellingen.
Hierbij is het belangrijk om de meerwaarde en de compatibiliteit te beschouwen van het MAS.
Dit hoofdstuk richt zich op het afstemmen van het MAS en de plaats ervan binnen lopende meetnetten.

De boerenlandvogelindex (farmland bird index, FBI) is een belangrijke indicator, waarbij de gegevens van een set aan broedvogelsoorten gerelateerd aan het agrarisch gebied internationaal opgevolgd worden.
Er wordt overwogen om deze indicator in de Europese natuurherstelwet op te nemen.
In Vlaanderen worden de gegevens van de Algemene Broedvogel tellingen (ABV) gebruikt om deze index te berekenen, gebaseerd op de soortenlijst die is afgestemd op de Europese soortenlijst en gevoed door de tellingen die.
De methodiek van ABV is gebaseerd

Dit ABV project loopt al sinds 2007 en is een langlopende monitoring van alle algemene broedvogels in ...
Een MAS netwerk over heel Vlaanderen kan hierbij niet het alle landbouwhokken ...

