# Ontwerp inzameling pilootgegevens 2022 - 2023 {#pilootgegevens}

## Informatiebehoefte-analyse

De vermelde projecten die we hebben besproken in hoofdstuk \@ref(historie) en hoofdstuk \@ref(historie) volstaan niet om aan alle monitoringnoden in Vlaanderen te voldoen.
Er is zowel een behoefte aan een meer verfijnd en betrouwbaar beeld van de toestand van vogels in het landbouwgebied in Vlaanderen (inclusief detectie van
regionale verschillen), als aan een beter inzicht in de oorzaken van de huidige trends en de effectiviteit van maatregelen om negatieve trends om te keren.

De monitoringnoden in meest brede zin zijn:

1.   **Beleidsmonitoring** (*macroniveau*) i.v.m. soorten of ruimere agrobiodiversiteit in het *landbouwgebied in Vlaanderen* focust op een breed spectrum aan soorten (bv. vogels, insecten, ...) en aangepaste landbouwpraktijken.
     De nadruk ligt op de impact van het beleid (GLB en  natuurbeleid) op lange termijn trends in het landbouwgebied.
De resulterende rapportering en de  daaruit afgeleide aanbevelingen zijn bruikbaar in een lange termijn beleidsplanning.
     Beleidsmonitoring overstijgt het evalueren van één instrument zoals beheerovereenkomsten maar  kan wel een belangrijk toetsingskader vormen.

2.   **Beheermonitoring** (*mesoniveau*) heeft als doel na te gaan of de uitgevoerde  beheermaatregelen op *gebiedsniveau* het gewenste vooropgestelde ecologische resultaat (effectiviteit) opleveren.
     Beheermonitoring wordt bij voorkeur uitgevoerd in prioritaire gebieden met hoge densiteit aan maatregelen en in aanliggende controlegebieden met een gelijkaardig potentieel maar zonder maatregelen.
     Hierbij worden op een voldoende fijn schaalniveau naast verschillende ecologische parameters (doelsoorten) (= responsvariabelen) ook voldoende gebiedskarakteristieken (bv. teelten,  perceelgroottes, permanente landschappelijke infrastructuur – onverharde wegen, houtkanten, ...) (= verklarende variabelen) meegenomen die het (verklarende) zeggenschap van de verzamelde ecologische data kunnen verhogen.
Rapportering en aanbevelingen laten toe om op middellange termijn maatregelen bij te sturen.

3.   **aanvullend verklarend onderzoek** (*microniveau*).
     Op basis van de resultaten van beleids- en beheermonitoring is het vaak aangewezen om aanvullend ook monitoring van bepaalde beheerindicatoren op microniveau of meer diepgaand soortspecifiek onderzoek uit te voeren om een beter inzicht te verkrijgen in de factoren die de waargenomen trends kunnen verklaren of om de ecologische validatie te doen van specifieke nieuwe of aangepaste maatregelen.
     O.a. de SWOT-analyse van het Soortenbeschermingsprogramma (SBP) akkervogels (in opmaak) onderschrijft deze noodzaak.
     Verschillende sleutelactoren werken hiervoor nauw samen waardoor binnen de uitvoeringstermijn van een instrument feedback mogelijk is naar de landbouwer en op middellange termijn een onderbouwde bijsturing (evidence-based) van bepaalde maatregelen mogelijk wordt.

Deze verschillende noden vergen een verschillend meetnetontwerp of onderzoeksopzet, die eventueel ook gedeeltelijk zou kunnen overlappen.
Beleidsmonitoring vraagt om een aselecte steekproef om onvertekende uitspraken te kunnen doen.
Naarmate de vraagstelling meer gericht is, zoals het geval is bij de vraag naar de effectiviteit van specifieke maatregelen voor een bepaalde soort, zal ook een meer gericht ontwerp nodig zijn.
Niettemin kan er naar synergie gestreefd worden tussen de verschillende niveaus van monitoring.
Een nodige voorwaarde voor synergie is dat meetmethoden zo goed mogelijk op elkaar worden afgestemd.

## Plan van aanpak

Binnen dit pilootproject werken we een strategie uit die toelaat om de monitoringnoden op het raakvlak tussen macro en mesoschaalniveau voor wat betreft de soorten die kunnen opgevolgd worden met het MAS telprotocol (i.e. voornamelijk vogels die courant voorkomen in landbouwgebied, evenals sommige zoogdieren die met dit telprotocol kunnen worden waargenomen).
We zullen deze aanpak uitwerken voor enerzijds de Oostelijke leemstreek en anderzijds de Moeren (zie \@ref(piloot-steekproefkader) voor de exacte ruimtelijke afbakening), omdat binnen deze gebieden er al MAS tellingen gebeuren sinds 2018 met een actieve vrijwilligerswerking.

We combineren de vragen om enerzijds een meer verfijnd en betrouwbaar beeld van de toestand van vogels in het landbouwgebied in Vlaanderen (inclusief detectie van regionale verschillen), met de vraag om een beter inzicht te krijgen in de effectiviteit van de maatregelen zonder hierbij te focussen op een individuele specifieke maatregel.
De meeste beschermingsmaatregelen worden geconcentreerd toegepast in de zogenaamde kerngebieden of prioritaire gebieden.
Het zijn ook deze gebieden waar de vroegere MAS tellingen zich op concentreerden.
De historische data laten ons dus al toe om na te gaan of er, gezamenlijk met de toename in oppervlakte aan beschermingsmaatregelen, er ook een verbetering te zien is in de populatiegroottes van de soorten.
Deze data kunnen ons echter niet vertellen of een eventuele verbetering zich misschien ook heeft voorgedaan buiten deze kerngebieden, waardoor we met minder grote stelligheid kunnen beweren dat de maatregelen een effect hebben.
Het is daarom nodig dat we het meetnet uitbreiden en ook gaan tellen in zones met weinig of geen beschermingsmaatregelen en daarbij moeten we ervoor zorgen dat deze zones zo goed mogelijk vergelijkbaar zijn met deze van de kerngebieden.
Het type van landbouwvoering moet vergelijkbaar zijn en dit hangt sterk af van onder andere de bodem, het reliëf en het klimaat.
Dit zijn aspecten die vrij goed gecapteerd worden door de landbouwstreken van België.
Binnen eenzelfde landbouwstreek (de Moeren ligt bijvoorbeeld in de Polders en de Oostelijke leemstreek maakt deel uit van de leemstreek) verwachten we dus gelijkaardige landbouwvoering.
Daarnaast, weten we dat - zeker voor akkervogels - de openheid van het landschap een sterk bepalende factor is voor het voorkomen van deze soorten.
Sommige soorten komen voor in zeer open landschappen en andere soorten komen eerder voor in half-open landschappen.
Deze twee elementen (landbouwstreek en openheid van het landschap) zullen dus sleutelelementen worden in ons meetnetontwerp en zullen ons enerzijds toelaten om "vergelijkbare" situaties te vinden binnen en buiten kerngebieden, en anderzijds, biedt de verkaveling in landbouwstreken een antwoord op de wens om ook zicht te krijgen op regionale verschillen in toestand en trend van relatieve populatiegroottes van de soorten.
Dit laatste zal nog niet mogelijk zijn met de data die tijdens dit pilootproject worden ingezameld, maar wordt wel mogelijk wanneer we dit "proof of concept" uitrollen naar de andere landbouwstreken in Vlaanderen (zie hoofdstuk \@ref(ontwerp-meetnet)).

Met deze aanpak beantwoorden we dus zowel de informatienoden voor beleidsmonitoring als de beheermonitoring op mesoniveau, althans wanneer uitgerold naar Vlaanderen.
Een belangrijke doelstelling van het pilootproject is dan ook de haalbaarheid en opschaalbaarheid van deze monitoring in te schatten zodat in de toekomst meer inzicht wordt verkregen in de effectiviteit van de geleverde inspanningen in zijn geheel (inclusief beheerovereenkomsten, soort(en)beschermingsprogramma's, conditionaliteiten, (pre-)ecoregelingen, agromilieuklimaatmaatregelen, niet-productieve  investeringen via het Vlaams Investeringsfonds, ...).

Onze aanpak laat ook toe om een deel van de bestaande tellocaties te behouden.
Binnen het pilootproject werd dit in de eerste plaats toegepast op de reeds bestaande tellocaties van het Meetnet Agrarische Soorten.
Principieel kan het principe dat we hiervoor gebruikt hebben echter ook worden toegepast op ABV telhokken (met daarbinnen tellocaties). 

In sectie \@ref(piloot-ontwerp) volgt een meer technische bespreking van de aanpak.

## Ontwerp van de gegevensinzameling {#piloot-ontwerp}

We overlopen volgende stappen:

-   Afbakening van het steekproefkader
-   Stratificatie
-   Steekproefgrootteberekening
-   Allocatie van de totale steekproefgrootte over de strata
-   De steekproeftrekking
-   Overlap met bestaande telpunten

### Afbakening steekproefkader {#piloot-steekproefkader}

We bouwen het steekproefkader op aan de hand van Open Streetmap data.

Intersectie landbouwstreek België met contour Vlaanderen en overlappend met prioritaire gebieden voor akkervogels.

:::: {.center data-latex=""}
::: {.minipage data-latex="{.5\linewidth}"}
hier ergens een kaart met de perimeters van de Moeren en de Oostelijke leemstreek
:::
::::

Exclusie van bepaalde landgebruiken:

-   https://wiki.openstreetmap.org/wiki/Key:leisure
   -   park

-   https://wiki.openstreetmap.org/wiki/Key:landuse
   -   residential
   -   military
   -   industrial
   -   cemetery

Verder vereenvoudigen van de polygonenkaart door:

-   alle polygonen samen te voegen tot 1 multipolygon (union)
bufferen met straal 20 m
-   overtollige vertices verwijderen met tolerantie 10 m
-   alle gaten (polygon holes) verwijderen

Exclusie van bepaalde landgebruiken

- https://wiki.openstreetmap.org/wiki/Key:leisure
    - park
- https://wiki.openstreetmap.org/wiki/Key:landuse
    - residential
    - military
    - industrial
    - cemetery


Verder vereenvoudigen van de polygonenkaart door:

- alle polygonen samen te voegen tot 1 multipolygon (union)
- bufferen met straal 20 m
- overtollige vertices verwijderen met tolerantie 10 m
- alle gaten (polygon holes) verwijderen



Bepalen geldige plaatsen waar telling kan uitgevoerd worden

Extractie uit Openstreetmap:

- https://wiki.openstreetmap.org/wiki/Key:highway
    - track
    - footway
    - path
    - cycleway
    - bridleway
    - tertiary
    - tertiary_link
    - unclassified

Maar met uitsluiting van holle wegen, omdat vanuit een holle weg de zichtbaarheid te beperkt is.
Een holle weg wordt in OSM aangeduid als highway=* + cutting=yes|both|hollow_way of historic=hollow_way.

Verder voegen we ook de waterlopen toe (in principe moet er een vrije strook van minstens 1 m zijn langs elke waterloop):

- https://wiki.openstreetmap.org/wiki/Key:waterway:
    - river
    - stream
    - tidal channel
    - canal
    - drain
    - ditch

Verwijderen van paden die overlappen met exclusiekaart.
Verwijderen van overlappende paden.


Punten langs de paden

Werkwijze:

- Langs alle paden worden op regelmatige afstanden van 50 m punten gelegd
- Daarna worden punten die op minder dan 40 m van elkaar liggen ruimtelijk gegroepeerd (dit gebeurt wanneer verschillende paden elkaar kruisen of op korte afstand parallel aan elkaar liggen) en uit elk van deze clusters wordt één punt overgehouden
- potentiële telpunten moeten op minstens 300 m van de grens gelegen zijn

_Niet_ gedaan, maar zou wellicht wel nuttig zijn:

> Langs autosnelwegen liggen vaak parallelle paden, vaak zelfs langs beide kanten van de snelweg. Dit kan in de steekproef tot gevolg hebben dat er met een hogere waarschijnlijkheid een punt wordt geselecteerd vlak bij een snelweg - gewoon omdat er veel van zulke punten zijn. Enerzijds is dat een realiteit van het terrein die een invloed heeft op de waarnemingen (vaak kraaien, buizerd langs snelwegen) en vrij zeker ook op de detecteerbaarheid (geluidsoverlast en beperkte zichtbaarheid). We willen selectie in de buurt van snelwegen niet volledig uitsluiten, maar ook niet te waarschijnlijk maken. Het zou daarom beter zijn om een extra exclusiecriterium in acht te nemen door een zone van 50m buffer rond de snelwegen uit te sluiten. Op die manier gaan er nog steeds punten zijn waarvan de telcirkels het effect van snelwegen omvatten, maar sluiten we punten die te dicht tegen snelwegen liggen uit.



Exclusie van potentiële telpunten / telcirkels

Exclusie op basis van landgebruiksamenstelling


Voor elk potentieel telpunt / telcirkel:

- landgebruik oppervlaktes

VITO 2019 landgebruikskaart



We gebruiken volgende regel als criterium voor telpunten die in aanmerkingen komen voor wat betreft de samenstelling van het landgebruik in een buffer van 300 m rond het punt:

- Akker + Grasland > 40% én Grasland + Bos + Struikgewas + Akker > 50%


De gebruikte landgebruikskaart dekt enkel het Vlaamse grondgebied.
Indien de telcirkel deels in een andere gewest / land gelegen is, zal het landgebruik daar ontbreken.
In de momenteel gebruikte berekening is dit "ontbrekend" landgebruik weggefilterd en slaat het oppervlakte-aandeel enkel op het deel van de telcirkel waar we data voor hebben.
Het kan dus zijn dat op de volledige telcirkel deze oppervlakte-aandelen verschillend zijn (en al dan niet zouden moeten uitgesloten worden volgens het criterium).


De kaart toont de punten die op deze manier niet meer in aanmerkingen komen.


Exclusie op basis van slechte zichtbaarheid

Hier is al gedeeltelijk rekening mee gehouden door holle wegen uit te sluiten.
Mogelijk zijn echter niet alle holle wegen gekend in Openstreetmap en er zijn ook andere landschapsconfiguraties die maken dat observatie van vogels lastig is.
Om hiermee rekening te houden kunnen we telpunten uitsluiten op basis van analyses van een gedetailleerde digitale oppervlakte kaart (DSM).

Een volledige 'viewshed' of 'visibility' analyse voor elk potentieel telpunt kost echter te veel rekentijd.
Een alternatief is daarom dat we deze analyse enkel uitvoeren voor geselecteerde punten en de uitkomst van de analyse gebruiken om geselecteerde punten met slechte zichtbaarheid te vervangen door andere (reserve)punten.


### Stratificatie-variabelen en andere hulpvariabelen {#piloot-stratificatie}

Berekening volledig gekende variabelen die relatie hebben met respons

Dit zijn interessante variabelen om in rekening te brengen bij het steekproefdesign.
Dit kan bijvoorbeeld door middel van stratificatie of door te zorgen dat de steekproef op een homogene manier de gradiënt van deze hulpvariabele(n) afdekt.

Voor elk potentieel telpunt / telcirkel:

- Beheerovereenkomst oppervlaktes: vooral de soortbeschermingsmaatregelen
- maat voor openheid van het landschap (cf. OLA, HOLA, KLA)
- oppervlakte-aandelen van hoofdteelten (landbouwgebruikspercelen)


*Oppervlakte-aandeel beheerovereenkomsten*

Toestand beheerovereenkomsten 2021.

Indeling voor niet-productieve gewassen / beheerovereenkomsten (instrumenten):

- soortbeschermingsmaatregelen
    - perceelsniveau
    - randen
- erosiemaatregelen
- bufferstroken

Voor de steekproeftrekking zijn vooral de oppervlakte aan soortbeschermingsmaatregelen van belang.
Eventueel verder opgesplitst in winter-, zomer- en jaarrondmaatregelen.





*Oppervlakte-aandeel hoofdteelt*

Belangrijkste teelten in 2020:


Een logische en veelgebruikte opdeling voor gewassen is:

- graangewassen (monocotylen zoals tarwe, gerst, etc..) 
- grasland (opdelen permanent en tijdelijk)
- mais
- aardappelen
- wortelgewassen (biet, chicorei, wortel)
- peulvruchten (erwt)
- groententeelt (kolen zoals bloemkool, brocolli, spruiten, prei, ajuin, sla)
- groenbemester (klavers, luzerne, mosterd) of koolzaad
- meerjarige fruitteelt (appel, peer, kers, ea)
- vlas
- andere (vb eenjarig fruitteelt) 

Hier gebruiken we de indeling volgens 'gewasgroep' zoals deze in de landbouwgebruikspercelenkaart zit.


*Openheid landschap*

We maken gebruik van het DSM (digitaal oppervlakte model - DHMV II Vlaanderen) en DTM (digitaal terrein model) op 5 m resolutie.
Werkwijze:

- berekening "canopy height model" (CHM) door verschil te berekenen tussen DSM en DTM. Dit geeft dan hoogte boven het maaiveld (gebouwen, bodem, struiken, ...).
- berekening van "positive topographic openness" (dit is een waarde tussen 0 en 2 in radians) door voor elke rastercel van het CHM in 8 kijkrichtingen na te gaan wat de gemiddelde hoek is t.o.v. zenith binnen een straal van 300m. Deze hoek geeft aan hoe plat het landschap is. Indien volledig plat is de hoek 90° (of 1.57 radians).
- met dit resultaat de gemiddelde (van de gemiddelde) topografische openheid berekenen in een cirkelvormig landschap rond elke cel met straal 300 m.
- deze gemiddelden zijn daarna ingedeeld in drie klassen:
    - OL open landschap (> 86,5°), 
    - HOL halfopen landschap (77,3° - 86,5°),
    - HGL halfgesloten landschap (71,6° - 77,3°)
    - GL (< 71,6°) gesloten landschap

Akkervogelgemeenschappen worden vaak ingedeeld volgens hun affiniteit met open landschap (OLA - Open landschap Akkervogels), half-open landschap (HOLA) en kleinschalig landschap (KLA).
Onder kleinschalig landschap verstaat men een landschap waar de percelen relatief klein zijn en het landschap in sterke mate dooraderd is door hagen, rietkragen en andere lijn- of puntvormige kleine landschapselementen (KLE's).
De manier waarop we openheid van het landschap hebben bepaald laat niet toe om KLA te bepalen zonder bijkomende berekeningen.
KLA zullen een subset zijn van wat wij HOL noemen, met name HOL waar de gemiddelde perceelsgrootte relatief klein is.


### Steekproefgrootteberekening {#piloot-steekproefgrootte}



### Allocatie steekproefgrootte over strata {#piloot-allocatie-strata}



### Steekproeftrekking {#piloot-steekproeftrekking}

- Stratificatie:
    - binnen vs buiten SBP perimeter
        - allocatiefactor 50%
    - OL vs HOL landschap
        - allocatiefactor proportioneel aan aantal potentiële telpunten (~ stratumoppervlakte)
- Gebalanceerde en goed gespreide trekking:
        - ruimtelijk (x en y coördinaten)
        - oppervlakte aandeel beheerovereenkomsten


Allocatie van de steekproefgrootte over de verschillende strata:

- Hier moeten we afweging maken tussen de precisie per stratum en precisie voor de leemstreek in zijn geheel.
    - Voor het geheel zou een allocatie evenredig een de oppervlakte van elk stratum wellicht de voorkeur hebben.
    - Indien we echter ook geïnteresseerd zijn in uitspraken voor elk stratum apart en in onderlinge vergelijkingen tussen de strata, dan is een allocatie waarbij in elk stratum evenveel punten liggen meer aangewezen.

Tussen deze twee scenario's zijn er veel tussenposities.
In het algemeen kunnen we voor een kostenoptimale allocatie gebruik maken van een formule die stelt dat de allocatie recht evenredig is met de oppervlakte van een stratum en de variabilitiet in een stratum en omgekeerd evenredig is met de vierkantswortel van de kosten van het veldwerk in het stratum.

Steekproefgrootte voor de Leemstreek (en Moeren) voor de pilootfase laten afhangen van wat er haalbaar is met professionelen en vrijwilligers:

- leemstreek: 350 punten per jaar?
- moeren: 60 punten per jaar?


In elk geval zal er een veelvoud van het vooropgestelde aantal telpunten getrokken worden.
Elk telpunt zal een volgnummer hebben.
De eerste (bv) 300 (laagste volgnummers) zullen dan de set zijn voor de leemstreek, die kan verdeeld worden over de medewerkers.
Indien een punt uitvalt, kan dit vervangen worden door het eerstvolgende uit de reeks dat nog niet toegewezen werd (het 301ste).
De methode garandeert dat deze nieuwe set ruimtelijk goed gespreid is en een aselecte steekproef is.

Temporeel design:

- elk punt wordt elk jaar opnieuw bezocht

N.B. voor de steekproef over Vlaanderen is het best mogelijk dat een ander temporeel design nodig is zoals een 'rotating panel design' of een 'augmented panel design'.



Uit het targets object `steekproef_zichtbaarheid` is er al een keuze gemaakt voor telpunten die op minder dan 300 m van elkaar gelegen zijn.
In dat geval is het telpunt met laagste `sample_order` weerhouden.



Kaart van de steekproef (enkel eerste batch van punten):


De meest open landschappen zitten volledig binnen de perimeter van het SBP plan.
De vergelijking van HOL binnen vs buiten plan en OL binnen vs buiten plan is dus bemoeilijkt omdat de gemiddelde openheid systematisch hoger zal liggen binnen de SBP perimeter.

Een ander confounding probleem is dat HOL en HGL gemiddeld noordelijker gelegen zijn buiten SBP perimeter.

Verder is ook duidelijk te zien dat veruit de meeste SB beheerovereenkomsten afgesloten zijn binnen de SBP perimeter.
De stratificatie binnen vs buiten SBP kunnen we dus effectief gebruiken als factor om na te gaan of er een effect is van deze maatregelen.
We zullen wel moeten corrigeren voor de confounders door de confounders op te nemen in een model en/of door de data te filteren met behulp van statistical matching technieken in functie van specifieke vraagstellingen over de effectiviteit van beheerovereenkomsten.

We zien wel dat de steekproef een goede afspiegeling is van de volledige populatie (boxplots voor steekproef en populatie zijn zeer gelijkend).


*Verwijderen van telpunten met slechte zichtbaarheid?*

In deze fase werden telpunten niet automatisch verwijderd op basis van de zichtbaarheidsindex.
De reden hiervoor is dat er nog tamelijk situaties zijn waar de zichtbaarheidsindex laag is, terwijl de terreinsituatie toch een goede zichtbaarheid toelaat.
De reden voor zulke 'vals positieven' zijn:

- bomenrijen waar je door kan kijken
- holle weg waar je mits je even op de kant klimt wel voldoende zichtbaarheid hebt
- punten langs 'waterwegen' liggen dieper in het landschap, terwijl je uiteraard niet in het water gaat staan maar op de oever er langs

De les die we hieruit leren is dat de zichtbaarheidsanalyse betere resultaten kan geven indien we de analyse niet enkel vanaf het exacte punt uitvoeren, maar voor een ruimere zone (van 25m) rond het punt (zone bewegingsvrijheid van de waarnemer).



### Overlap met bestaande telpunten {#piloot-overlap}

Aanpak _bestaande_ MAS telpunten:

- nagaan welke 'voldoende dichtbij' gelegen zijn bij getrokken telpunten
    - op minder dan 300 m afstand => nieuw telpunt vervangen door bestaand telpunt 

Achteraf is deze regel versoepeld en zijn ook bestaande punten die op iets grotere afstand lagen als vervanging opgenomen.

<!--Een alternatief is dat we de bestaande telpunten toevoegen aan de set van potentiële telpunten en deze een hogere inclusiekans geven - eventueel zelfs afhankelijk van de "kwaliteit" van het bestaand telpunt (bv aantal jaren gemonitord). Deze aanpak is echter veel moeilijker om achteraf de gegevens te analyseren op een correcte manier (veel makkelijker om door een reviewer van de statistiek onderuit gehaald te worden)
-->

### Manuele controle

De steekproef werd geëxporteerd naar een kml bestand en gedeeld als een kaart in google maps met de tellers.
Na controle van de punten op bereikbaarheid, zichtbaarheid, overlap met andere punten, werden sommige punten verwijderd en vervangen door een ander punt.

De verwijderde punten:


Daarna werden punten toebedeeld aan tellers.
Tellers kunnen ook punten claimen door dit aan te geven in de google maps kaart.

