---
title: "Meetnet Agrarische Soorten: van lokale pilootstudie tot een Vlaams monitoring instrument"
subtitle: "Steekproefdesign voor de monitoring van agrarische fauna in Vlaanderen"
author:
  - name:
      given: "Ward"
      family: "Langeraert"
    email: "ward.langeraert@inbo.be"
    orcid: "0000-0002-5900-8109"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Hans"
      family: "Van Calster"
    email: "hans.vancalster@inbo.be"
    orcid: "0000-0001-8595-8426"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Nicolas"
      family: "Van Overmeeren"
    email: "nicolas.vanovermeeren@inbo.be"
    orcid: "0009-0005-2174-672X"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Johannes"
      family: "Jansen"
    email: "johannes.jansen@inbo.be"
    orcid: "0009-0005-2436-5236"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
    corresponding: true
reviewer:
  - name:
      given: "Koen"
      family: "Devos"
    email: "koen.devos@inbo.be"
    orcid: "0000-0001-7265-6349"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
lang: nl
style: INBO
floatbarrier: subsubsection
keywords: "akkerfauna; monitoring; akkervogels; meetnet; landbouw"
community: "inbo"
publication_type: report
funder: Instituut voor Natuur- en Bosonderzoek (INBO)
rightsholder: Instituut voor Natuur- en Bosonderzoek (INBO)
bibliography: [software.bib, references.bib, layers.bib]
link-citations: TRUE
site: bookdown::bookdown_site
year: 2024
reportnr: 1
cover_photo: cover.jpg
cover: cover.jpg
cover_description: Gele kwikstaart (_Motacilla flava_). (© Johannes Jansen)
output:
  INBOmd::gitbook: default
  INBOmd::pdf_report: default
  INBOmd::epub_book: default
# Don't run the format below.
# Only required for RStudio to recognise the project as a bookdown project.
# Hence don't use 'Build all formats'.
  bookdown::dontrun: default
---

# Dankwoord {.unnumbered}

Deze studie is tot stand gekomen dankzij een samenwerkingsovereenkomst tussen het INBO en

# Samenvatting {.unnumbered}

<!-- description: start -->

...

<!-- description: end -->

# Aanbevelingen voor beheer en/of beleid {.unnumbered}

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  cache = FALSE,
  warning = TRUE,
  error = FALSE,
  message = TRUE
)
library(tidyverse)
library(INBOtheme)
if (interactive()) {
  theme_set(theme_inbo(base_size = 10))
} else {
  switch(
    opts_knit$get("rmarkdown.pandoc.to"),
    html = {
      opts_chunk$set(dev = "png", dpi = 72)
      theme_set(theme_inbo(base_size = 12))
    },
    latex = {
      opts_chunk$set(dev = "cairo_pdf", dpi = 300)
      theme_set(theme_inbo(base_size = 9))
      update_geom_defaults("point", list(size = 1.5))
    },
    epub3 = {
      opts_chunk$set(dev = "png", dpi = 300)
      theme_set(theme_inbo(base_size = 12))
    }
  )
}
```

```{r googledrive, include = FALSE}
# authenticatie google drive
library(googledrive)
googledrive::drive_auth(email = "*@inbo.be")

# source functie om figuren te downloaden van google drive
source("../include_from_drive.R")

# google drive verwijzing naar figuren
sdf <- shared_drive_find("PRJ_MBAG") %>%
  drive_ls(pattern = "4a_mas", type = "folder") %>%
  drive_ls(pattern = "rapporten", type = "folder") %>%
  drive_ls(pattern = "mas_piloot_steekproefdesign", type = "folder") %>%
  drive_ls(pattern = "media", type = "folder")

figs <- sdf %>%
  drive_ls(recursive = TRUE) %>%
  drive_reveal(what = "webViewLink") %>%
  drive_reveal(what = "webContentLink") %>%
  drive_reveal(what = "path") %>%
  drive_reveal(what = "fileExtension")

# get figures from google drive
# set overwrite = TRUE if necessary!
for (file_name in figs$name) {
  include_from_drive(name = file_name, figures = figs, overwrite = FALSE)
}
```
